server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productService
                fallbackUri: forward:/productFallback
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventories/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryService
                fallbackUri: forward:/inventoryFallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/